"""lib/options_pricing.py must agree with rs_dashboard/lib/optionsPricing.ts.

The fixture is generated by the TypeScript library (UPDATE_PARITY=1 node --test lib/optionsPricing.test.ts in rs_dashboard).
If this fails after a formula change, port the change to lib/options_pricing.py (or regenerate the fixture if the change was intended
on both sides) so the dashboard and the strategies keep pricing off the same maths.
"""
import json
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from lib import options_pricing as op  # noqa: E402

FIXTURE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "rs_dashboard", "lib", "optionsPricing.parity.json")
with open(FIXTURE, encoding="utf-8") as fh:
    CASES = json.load(fh)

TOL = 1e-9


def close(a, b, tol=TOL):
    return abs(a - b) <= tol * max(1.0, abs(b))


class OptionsPricingParity(unittest.TestCase):
    def test_constants_match_typescript(self):
        with open(os.path.join(os.path.dirname(FIXTURE), "optionsPricing.ts"), encoding="utf-8") as fh:
            ts = fh.read()
        self.assertIn(f"RISK_FREE_RATE = {op.RISK_FREE_RATE}", ts)
        self.assertIn(f"CALENDAR_DAYS_PER_YEAR = {op.CALENDAR_DAYS_PER_YEAR}", ts)

    def test_exact_greeks(self):
        for c in CASES["greeks"]:
            g = op.compute_bs_greeks_exact(c["type"], c["U"], c["K"], c["t"], c["iv"], c["r"], c["isFutures"])
            for field in ("price", "delta", "gamma", "theta", "vega", "rho", "vanna", "vomma", "charm"):
                self.assertTrue(close(getattr(g, field), c["out"][field]), f"{field} {getattr(g, field)} vs {c['out'][field]} for {c}")

    def test_implied_vol(self):
        for c in CASES["ivs"]:
            got = op.implied_vol(c["type"], c["U"], c["K"], c["t"], c["price"], 0.065, c["isFutures"])
            if c["out"] is None:
                self.assertIsNone(got, c)
            else:
                self.assertIsNotNone(got, c)
                self.assertTrue(close(got, c["out"], 1e-7), f"{got} vs {c['out']}")

    def test_clock_and_roll(self):
        for c in CASES["clock"]:
            self.assertTrue(close(op.time_to_expiry_years(c["expiry"], c["now"]), c["out"]), c)
        for c in CASES["roll"]:
            self.assertTrue(close(op.roll_forward(c["F"], c["from"], c["to"], now=c["now"]), c["out"]), c)

    def test_risk_neutral_prob_above(self):
        for c in CASES["prob"]:
            self.assertTrue(close(op.risk_neutral_prob_above(c["S"], c["K"], c["t"], c["iv"], 0.065), c["out"]), c)

    def test_greeks_for_leg_recipe(self):
        for c in CASES["legs"]:
            fut = c["future"] or {}
            got = op.greeks_for_leg(
                c["type"], c["strike"], c["expiry"], c["spot"], mark=c.get("mark"), chain_iv=c.get("chainIv"),
                fallback_iv=c.get("fallbackIv"), future_price=fut.get("price"), future_expiry=fut.get("expiry"), now=c["now"],
            )
            if c["out"] is None:
                self.assertIsNone(got, c)
                continue
            self.assertIsNotNone(got, c)
            self.assertEqual(got.iv_source, c["out"]["ivSource"], c)
            self.assertTrue(close(got.iv, c["out"]["iv"], 1e-7), c)
            self.assertTrue(close(got.forward, c["out"]["forward"]), c)
            for field in ("price", "delta", "gamma", "theta", "vega"):
                self.assertTrue(close(getattr(got.greeks, field), c["out"][field], 1e-6), f"{field} {c}")


    def test_vectorised_iv_agrees_with_scalar(self):
        import numpy as np
        rows = [(c["type"], c["U"], c["K"], c["t"], c["price"], c["isFutures"]) for c in CASES["ivs"]]
        got = op.implied_vols(
            [r[4] for r in rows], [r[1] for r in rows], [r[2] for r in rows], [r[3] for r in rows],
            [r[0] == "CE" for r in rows], [r[5] for r in rows],
        )
        for (typ, U, K, t, price, fut), v in zip(rows, got):
            scalar = op.implied_vol(typ, U, K, t, price, 0.065, fut)
            if scalar is None:
                self.assertTrue(np.isnan(v), (typ, U, K, t, price, fut, v))
            else:
                self.assertAlmostEqual(v, scalar, places=5, msg=str((typ, U, K, t, price, fut)))


    def test_option_type_is_normalised_and_typos_raise(self):
        a = op.compute_bs_greeks_exact("CE", 22500, 22600, 0.05, 0.14).delta
        self.assertEqual(op.compute_bs_greeks_exact("ce", 22500, 22600, 0.05, 0.14).delta, a)
        self.assertEqual(op.compute_bs_greeks_exact("CALL", 22500, 22600, 0.05, 0.14).delta, a)
        self.assertLess(op.compute_bs_greeks_exact("pe", 22500, 22600, 0.05, 0.14).delta, 0)
        for fn in (
            lambda: op.compute_bs_greeks_exact("XX", 22500, 22600, 0.05, 0.14),
            lambda: op.price_option("", 22500, 22600, 0.05, 0.14),
            lambda: op.implied_vol("C E", 22500, 22600, 0.05, 40),
        ):
            with self.assertRaises(ValueError):
                fn()

    def test_price_option_guards(self):
        self.assertEqual(op.price_option("CE", 0, 22500, 0.05, 0.14), 0.0)      # non-positive underlying: intrinsic, never an exception
        self.assertEqual(op.price_option("PE", 22000, 0, 0.05, 0.14), 0.0)
        self.assertEqual(op.price_option("CE", 22600, 22500, 0.0, 0.14), 100.0)  # no time left: intrinsic


if __name__ == "__main__":
    unittest.main()
