import { NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs';
import { PROJECT_ROOT } from '@/lib/pyExec';

// Serves the OpenStatz tearsheet run_backtest_cli.py writes to debug/. Same shape
// as app/api/momentum/report/route.ts: a single fixed filename, never taken from
// the request, since this file lives outside rs_dashboard/public and is
// regenerated on every run.
const TEARSHEET_FILE = path.join(PROJECT_ROOT, 'debug', 'vectorbt_tearsheet.html');

export async function GET() {
  let body: Buffer;
  try {
    body = fs.readFileSync(TEARSHEET_FILE);
  } catch {
    return NextResponse.json(
      { success: false, error: 'No tearsheet found yet — run a backtest first.' },
      { status: 404 }
    );
  }

  return new NextResponse(new Uint8Array(body), {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': 'inline; filename="vectorbt_tearsheet.html"',
      // Regenerated by every backtest run — a cached copy would show stale results.
      'Cache-Control': 'no-store',
    },
  });
}
