import { NextRequest, NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs';
import { DEBUG_DIR } from '@/lib/strategyRegistry';

// Serves the backtest artifacts that scripts/analysis/backtest_momentum_portfolio.py writes
// into debug/. They live outside rs_dashboard/public and are regenerated on every run, so
// they cannot be static assets.
//
// The filename is NEVER taken from the request. The `type` parameter selects a row from this
// fixed table instead, so no user input reaches the filesystem path — a `?file=` style route
// here would be a directory-traversal read of the whole project.
const REPORTS = {
  plot: {
    file: 'momentum_backtest_plot.html',
    contentType: 'text/html; charset=utf-8',
    inline: true,
  },
  tearsheet: {
    file: 'momentum_tearsheet.html',
    contentType: 'text/html; charset=utf-8',
    inline: true,
  },
  excel: {
    file: 'momentum_backtest.xlsx',
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    inline: false,
  },
} as const;

type ReportType = keyof typeof REPORTS;

export async function GET(request: NextRequest) {
  const type = request.nextUrl.searchParams.get('type') ?? 'plot';
  if (!Object.prototype.hasOwnProperty.call(REPORTS, type)) {
    return NextResponse.json(
      { success: false, error: `Unknown report type. Expected one of: ${Object.keys(REPORTS).join(', ')}` },
      { status: 400 }
    );
  }

  const report = REPORTS[type as ReportType];
  const filePath = path.join(DEBUG_DIR, report.file);

  let body: Buffer;
  try {
    body = fs.readFileSync(filePath);
  } catch {
    return NextResponse.json(
      {
        success: false,
        error: `${report.file} not found. Generate it with: `
          + '(after activating the venv) python scripts/analysis/backtest_momentum_portfolio.py',
      },
      { status: 404 }
    );
  }

  return new NextResponse(new Uint8Array(body), {
    headers: {
      'Content-Type': report.contentType,
      'Content-Disposition':
        `${report.inline ? 'inline' : 'attachment'}; filename="${report.file}"`,
      // Regenerated by every backtest run — a cached copy would show stale results.
      'Cache-Control': 'no-store',
    },
  });
}
